config/routes.rb
Rails.application.routes.draw do
  resources :art_works

  devise_for :admins
  root "home#Index"
  
  get "/about" => "home#About", as: :about

  get "/contact" => "home#Contact", as: :contact

  post "/send_contact" => "home#Send_Contact", as: :send_contact

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/art_work.rb
class ArtWork < ActiveRecord::Base

  has_attached_file :Image,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  def s3_credentials
    {:bucket => ENV["AWS_BUCKET"], :access_key_id => ENV["AWS_ACCESS_KEY_ID"], :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end

  validates_attachment_content_type :Image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/art_works_controller.rb
class ArtWorksController < ApplicationController
  def index
    @art_works = ArtWork.all
  end

  def show
    @art_work = ArtWork.find(params[:id])
  end

  def new
    @art_work = ArtWork.new
  end

  def create
    @art_work = ArtWork.new(art_work_params)
    if @art_work.save
      flash[:notice] = "Artwork has been saved"
      redirect_to action: "Index"
    else
      flash[:alert] = "Artwork failed to save"
      render "Index"
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  def art_work_params
    params.require(:art_work).permit(:Title, :Technique, :Height, :Width, :Price, :Sold, :Description, :Image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :authenticate_user!

  def Index
  end

  def About
  end

  def Contact
    @contact_info = ContactInfo.new
  end

  def Send_Contact
    @contact_info = ContactInfo.new(contact_info_params)
    ContactMailer.contact_email(@contact_info).deliver
    flash[:info] = "Contact message sent..."
    redirect_to action: "Index"
  end

  def contact_info_params
    params.require(:contact_info).permit(:Name, :Email, :PhoneNumber, :Message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/art_works_helper.rb
module ArtWorksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/art_works/edit.html.erb
<h1>ArtWorks#edit</h1>
<p>Find me in app/views/art_works/edit.html.erb</p>

app/views/art_works/index.html.erb
<table>
  <%- @art_works.each do |art|-%>
    <tr>
      <td><%=link_to art.Title, art_work_path(art.id)-%></td>
      <td><%=art.Technique-%></td>
      <td><%= "#{art.Height}X#{art.Width}" -%></td>
      <td><%=art.Price-%></td>
      <td><%=art.Sold ? "Sold" : "" -%></td>
      <td><%=truncate(art.Description, :length => 20)-%></td>
      <td><%= image_tag art.Image.url(:thumb)-%></td>
    </tr>
  <%-end%>
</table>

app/views/art_works/new.html.erb
<h1>ArtWorks#new</h1>
<p>Find me in app/views/art_works/new.html.erb</p>

<%= simple_form_for @art_work do |f| -%>
  <%= f.input :Title -%>
  <%= f.input :Technique -%>
  <%= f.input :Height -%>
  <%= f.input :Width -%>

  <%= f.input :Price -%>
  <%= f.input :Sold -%>
  <%= f.input :Description -%>
  <%= f.input :Image -%>
  <%= f.button :submit -%>
<%- end -%>

app/views/art_works/show.html.erb
<table>
  <tr>
    <td>Title:</td>
    <td><%=@art_work.Title-%></td>
  </tr>
  <tr>
    <td>Technique:</td>
    <td><%=@art_work.Technique-%></td>
  </tr>
  <tr>
    <td>Measurements:</td>
    <td><%= "#{@art_work.Height}X#{@art_work.Width}" -%></td>
  </tr>
  <tr>
    <td>Price:</td>
    <td><%=@art_work.Price-%></td>
  </tr>
  <tr>
    <td>Sold?:</td>
    <td><%=@art_work.Sold ? "Sold" : "" -%></td>
  </tr>
  <tr>
    <td>Description:</td>
    <td><%=@art_work.Description-%></td>
  </tr>
</table>
<br />
<br />
<%= link_to "Full Image", @art_work.Image.url -%>
<br />
<br />
<%= image_tag @art_work.Image.url(:medium) %>

app/views/home/About.html.erb
<h1>About K</h1>
<p>Here is some infomation about the artist</p>

app/views/home/Contact.html.erb
<h1>Contact Form</h1>


<%= simple_form_for(@contact_info, :url => send_contact_path, html: { class: 'form-horizontal' }) do |f| -%>
  <%= f.input :Name -%>
  <%= f.input :Email -%>
  <%= f.input :PhoneNumber -%>
  <%= f.input :Message -%>
  <%= f.submit -%>
<%-end -%>


<form role="form" class="form-horizontal">
  <div class="form-group">
    <label class="control-label col-sm-2">Name</label>
    <div class="col-sm-7">
      <input class="form-control" type='text'></input>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2">Email</label>
    <div class="col-sm-7">
      <input class="form-control" type='email'></input>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2">Phone Number</label>
    <div class="col-sm-7">
      <input class="form-control" type='tel'></input>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2">Message</label>
    <div class="col-sm-7">
      <textarea class="form-control" type='text-area'></textarea>
    </div>
  </div>
  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-7">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
  </div>
</form>

app/views/home/Index.html.erb
<h1>K-Painting</h1>
<p>This is where the Painting will go.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kpainting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="admin_nav">
    <% if admin_signed_in? %>
      Logged in as <strong><%= current_admin.email %></strong>.
      <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>